import os
import platform
import logging
import subprocess

log = logging.getLogger("walkie")

# Path to the cached dumpkeys output generated by setup-wayland.sh
_DUMPKEYS_CACHE = os.path.join(
    os.path.expanduser("~"), ".whisper-walkie", "dumpkeys.cache"
)


def _patch_pynput_dumpkeys() -> None:
    """Monkey-patch subprocess.check_output so pynput's dumpkeys call
    uses our cached output instead of requiring root.

    pynput's uinput backend calls ``dumpkeys --full-table --keys-only``
    at import time, which requires /dev/console access (root only).
    Our setup-wayland.sh generates this cache via pkexec.  We intercept
    the subprocess call and return the cached data.
    """
    if not os.path.isfile(_DUMPKEYS_CACHE):
        return

    try:
        with open(_DUMPKEYS_CACHE, "rb") as f:
            cached_data = f.read()
    except Exception:
        return

    _original_check_output = subprocess.check_output

    def _patched_check_output(cmd, *args, **kwargs):
        if isinstance(cmd, list) and len(cmd) >= 1 and cmd[0] == "dumpkeys":
            return cached_data
        return _original_check_output(cmd, *args, **kwargs)

    subprocess.check_output = _patched_check_output


def _configure_pynput_backend() -> None:
    """Select the correct pynput backend before it is imported.

    On Wayland, pynput's default ``xorg`` backend uses XRecord which is
    completely non-functional — the listener thread starts but silently
    receives zero key events.  The ``uinput`` backend reads ``/dev/input/``
    via ``evdev`` and works correctly on Wayland (requires the user to be
    in the ``input`` group).

    This MUST be called before any ``import pynput`` statement.
    """
    if platform.system() != "Linux":
        return
    session_type = os.environ.get("XDG_SESSION_TYPE", "").lower()
    if session_type == "wayland":
        # Only set keyboard to uinput — there is no uinput mouse backend.
        # PYNPUT_BACKEND (global) is intentionally NOT set so mouse
        # falls back to xorg or dummy.
        os.environ.setdefault("PYNPUT_BACKEND_KEYBOARD", "uinput")
        _patch_pynput_dumpkeys()


def get_backend():
    """Factory: returns the appropriate PlatformBackend for the current OS."""
    system = platform.system()

    if system == "Windows":
        from .windows import WindowsBackend
        return WindowsBackend()
    elif system == "Darwin":
        from .macos import MacOSBackend
        return MacOSBackend()
    elif system == "Linux":
        _configure_pynput_backend()
        from .linux import LinuxBackend
        return LinuxBackend()
    else:
        raise RuntimeError(f"Unsupported platform: {system}")
